### ISSUE TITLE
Consolidate Various Install Instructions

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#123]
This is a larger vision to try and reduce the footprint of breaking changes to various setup procedures which may discourage a user from using Substrate or other ecosystem projects.

Tangible goals, in order of execution:

- [ ] A single markdown file which describes the instructions to install and use any product
- [ ] A docusaurus plugin to be able to copy either the whole markdown file or specific sub sections into another document, without having to rewrite the content.
- [ ] A docsify plugin to do the same (already works, but we need to add sub-section functionality for optimal use)
- [ ] A rustdocs plugin to do the same (no idea if this is possible)

**Comment by JoshOrndorff** [comment]
Oh nice. I just made a similar comment when reviewing https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/119

I definitely agree with the goal / vision. But I think writing plugins to copy the content to various places is overkill. What if tutorials just start with,

This tutorial assumes you already have a working [substrate developer environment](#) and the link goes to the single markdown document. It could even be a revised version of this page (possibly with details added) https://substrate.dev/docs/en/quickstart/installing-substrate.

I actually think "set up a developer environment" is a better phrasing than "install" since most people don't want to just install and run substrate, they want to hack with it.

**Comment by shawntabrizi** [comment]
I think there is value in not having a user jump to a bunch of different pages to complete a task. Especially I envision that we may only want the user to follow one section of a page for a particular tutorial.

That being said I agree this could be overkill. I probably wont attempt to do this in the near future so maybe we can do your idea as a step one and see how it works.

**Comment by kaichaosun** [comment]
From the experience to use other tools, like [docusaurus](https://docusaurus.io/docs/en), there are rare cases that make the contents duplicated in a lot of places.

A progressive structure for `Docs` will be helpful for users to be more immersed.

Then as Joshy proposed, we can have links in pages for the pre-requirements which depend on another section in another page.
