### ISSUE TITLE
Vision for Substrate 2.0 Docs

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#166]
As we move closer to a stable version of Substrate 2.0, it is important to align our goals around the documentation effort here to ensure we continue to tell a clear and concise story around the product.

This vision builds upon the existing [Vision for Substrate 1.0 Docs](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/46), so treat these visions as cumulative.

# The Story

In the Substrate v1.0 docs, we told our users how they can use Runtime modules from the Substrate Runtime Module Library and/or build build their own modules.

We explained at a high level how the Runtime works, and even dug into some of the finer details explaining the magic around how the runtime is constructed, starting at an individual module, up through the construct runtime macro, into the metadata which ultimately is exposed through our JavaScript APIs.

In v2.0, our goal should be to extend this story while introducing new development pathways for our users. We should have stories for:

* Working with Smart Contracts on Substrate
    * Working with and contributing to the ink! language
    * Working with and understanding how the SRML Contracts module works
* Building/Launching Production Ready Blockchain Networks
    * Fees system
    * Telemetry
    * Bootstrap Nodes
    * Runtime Upgrade Details
    * Using our Governance
    * (edit and add other bullets here)

## Working with Smart Contracts on Substrate

There are two distinct parts of the Smart Contract story on Substrate:
* SRML Contracts: A runtime module which enables the execution of Wasm Smart Contracts on Substrate
* ink!: The Rust eDSL we have build for writing smart contracts for `srml-contracts`

These docs may become quite large on their own, and may justify their own section within the Substrate Developer Hub, separate from the other Runtime and Fundamentals docs. To be determined...

### SRML Contracts

The SRML Contracts module is the most complicated runtime module in Substrate. Among it's numerous genesis configuration settings, it also have many specific implementation details which make it hard for users to know exactly how it all works.

Our goal should be to make it clear to users:
* How SRML Contracts Module works at a low level
* How they can use the SRML Contracts module in their own Substrate blockchain

To paint a picture of `srml-contracts` at a low level, we will need to cover a number of topics:
* Transaction Lifecycle (from the start to the end of a transaction, what happens)
* Gas + Gas Metering
* State Rent
* Transaction Reverting
* Genesis Configuration Settings
* Contract Deployment
* Contract Upgrades (maybe?)
* Contract Module APIs (for possibly building other languages which work)
* (edit to add more)

We also should expect that a number of our users coming to work with SRML Contracts module have come from a background on other popular smart contract platforms like Ethereum. We should probably have documentation specific to these users to help clarify similarities and differences.

Finally, once users know how it all works, they will want to use it themselves, so any fine details related to enabling the module, configuring it correctly, and building other ecosystem tools for their users to use it on their blockchain is needed.

This includes interactions between other modules calling into smart contracts directly through the contracts module.

### ink!

ink! being just one of the possible languages for developing against SRML Contracts means that in the long term, it may make sense to move ink! docs out of the Substrate Developer Hub.

However, for the time being, there is not enough substance behind the documentation for ink! to justify a seperate platform, which may cause confusion for our users. Instead, for the time being, SRML Contracts and ink! docs will live together and should tell a good story with one another.

Within ink! we should try to explain:

* How ink! is generally structured and works
* How you can contribute to ink!
* The test environment
* The layer between ink! and `srml-contracts`
* How cross contract calls work
* How contract to module calls work (async)
* Storage Structure of ink!
* (edit to add more)

One thing we will struggle with here is that ink! is still quite early in development, and lags behind the features available in the `srml-contracts` module. We should keep this in mind when writing docs (such as focusing on the more stable aspects of ink!) and when we tell users about our docs (that things are still in progress and may get updated frequently).

## Building/Launching Production Ready Blockchains

As the Polkadot Network release comes around the corner, more and more users who have been developing on Substrate will want to actually publish their chains to production, either as a solo-chain, or even a Parachain.

We should have documentation around the specific information developers need to be able to do this successfully from day 0, rather than having to learn from all the mistakes we have probably made ourselves.

This involves:

* Adding fees to all of the modules included in their runtime
* Steps, guidelines, and tips for auditing their own blockchain runtime
* Setting up bootstrap nodes, connecting a network together
* Creating and releasing Substrate nodes
* Integrating their node with our telemetry services
* Integrating their node with block explorers (maybe?)
* What kinds of on-chain Runtime upgrades they can make and how to do them safely
* Adding our default governance systems to their chains and using it in production
* Hard fork upgrades
* (edit to add more)

# Explicit Changes Needed from v1.0 Docs

Here is a list of notable items we will need to fix when moving from v1.0 to v2.0 docs. Mostly breaking changes in Substrate.

* We need to patch all breaking changes to Substrate development
    * The use of `As` which is now `from/into`
    * Updates to `decl_module`
    * Deprecated/new modules
* Use of Substrate module crates rather than in-runtime modules
* Bigger emphasis on generics
* Move away from or fix our `substrate-up` script story
* Migrate Recipes to use working module templates
* (edit to add more)

**Comment by JoshOrndorff** [comment]
IMHO the contracts/ink stuff if overemphasized in that plan. I'm definitely not against documenting contracts and ink, but I hesitate to make it such a big part of the story for v2.0. And I hope not to spend that portion of my own time working on contracts and ink.

I would prefer to emphasize
* Runtimes can be easily composed from existing modules
  * tightly-coupled modules
  * loosely-coupled modules
  * standalone modules
* Pluggable consensus
  * Not only is the runtime logic customizable, but the consensus game being played over it can be hot-swapped
  * Discuss how "forkless upgrades" apply (or not) to consensus changes
* Revise story around starting a new runtime
  * Replace `substrate-node-new` with a UI tool that allows developers to specify which SRML modules should be included in their runtimes.

**Comment by shawntabrizi** [comment]
My emphasis on the Contracts module and developing on ink! is proportional to the number of questions and users I see struggling to use these tools. It also seems to be in alignment with where we want our users to be developing and pushing the boundaries, but confirmation here would help.

On the other hand, I see very few people about topics like pluggable consensus, nor do I think it is in a proper place to be something we document. @rphmeier should be able to tell us better here.

I admit, these observations are not measured.

**Comment by 4meta5** [comment]
I think we need to invest significant time/effort covering the nuances of module development and better defining which applications are better suited as modules vs smart contracts (which is still a very open question). 

With this in mind, I would prefer to focus on demonstrating how users can use our governance and also design/build their own governance systems. This aligns with @shawntabrizi  point on "Building/Launching Production Ready Blockchain Networks". 

There are a lot of new patterns in the master branch `elections`, `collective`, `staking`, and `democracy` modules that could be explained well through high-level docs/tutorials -- I plan to cover some of these patterns in an upcoming [tutorial](https://github.com/4meta5/daotown).

**Comment by JoshOrndorff** [comment]
> emphasis on the Contracts module and developing on ink! is proportional to the number of questions and users I see struggling to use these tools

We've seen in that past that people _think_ they want smart contracts because in other platforms smart contracts are _the_ way to write dApps. Part of what we want to do is help users understand that deploying a contract on an existing chain is not the only way to build your dApp.

> I see very few people [ask] about topics like pluggable consensus
That's because it's new and innovative. Most projects have no such concept and people don't know to ask about it. We should help them see the merit. As I've mentioned many of my colleagues from the extended RChain family love the idea of substrate, but consider it a no-go without dag-based consensus.

**Comment by shawntabrizi** [comment]
@JoshOrndorff I could see pluggable consensus being a fine topic to cover, but I dont think it makes sense set it as a milestone which needs to be done by v2.0. Seems more like a personal effort, done when possible type thing. This is of course my opinion. If you feel passionately about this topic being something we directly focus on and call out as part of the v2.0 milestone, let's get that direction from @gavofyork or others on our leadership team.

Ultimately it comes down to limited resources and prioritization. When push comes to shove, we need to agree on a set of docs/topics which need to reach the finish line. 

In regards to smart contracts, I have witnessed a number of events actually the opposite of what you mentioned. Many people want to take their existing smart contracts and turn them directly into runtime modules, which would **not** be the right decision in most cases. As @4meta5 pointed out, there is still confusion when to use a module vs smart contract. As of right now [this stackoverflow post I made](https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract) is the only thing which really touches on the topic.

I have heard from other presentations that smart contracts may very well be used regularly as a platform for testing potential modules in a way that is less performant, but strictly safer to the network.

Finally, features like smart contract to runtime calls and vice versa are totally new and unique feature to Substrate which many people have been struggling to hack around for the time being.

@4meta5 I totally agree with where you want to go here. I think it makes sense to have users understand at a high level how Substrate's default governance system works in a solo-chain and parachain situations. In addition to the tutorials, it seems to me that it would be good to have additional high level documentation which covers similar topics that you teach (like a custom origin), but in the context of how Substrate does it. (real documentation is what I am looking for in addition to learning material)

We should also add to the v2.0 milestone migration of the recipes to fully working modules as we discussed.

**Comment by kaichaosun** [comment]
## Improve the Docs
The Docs should be the most important part in the hub.

### Proposals
1.**Target**: by exploring Docs, dev can learn how to build **custom blockchain** and **smart contract** (we may move it out in the future). There is no need to redirect to other resources to complete the above target.

In the sidebar, we should have the following content just under **Getting Started**. 
The user can look at the sidebar and know **what Substrate provides**, even they are not building anything yet. 
The content should contain **general concepts** around Substrate and **minimal** & **workable** code.

1.1 **Build Custom Blockchain**
  * Setup local network
  * Add your custom module
  * Add test (TBD)
  * Interact with your module;
  * Promote it to prod (when ready)
  * Connect to polkadot (when ready)

1.2 **Build Smart Contract**
  * Setup smart contract chain
  * Write your first contract
  * Deploy it to local
  * Interact with your contract
  * Promote it to the famous chain (TBD)

2.**Target**: Split between the Substrate basic knowledge and advanced knowledge. By exploring basics, the user can get quite well understanding around commonly used concepts in Substrate development. By exploring advanced parts, the user can know more about data storage layer, p2p connection, macros, pluggable consensus, security, etc.

### Improve tutorials
Too many resources make user **hard to find** really valuable one. Clarify what should be put into tutorials: 
* The **well documented, scenario-based, end-to-end workshops** are best to put into tutorials and highlighted. 
* **Small but valuable enough resources** can also put in, but not highlighted.

Other **small tips, high-quality blogs, community projects** should be put into either recipes or awesome substrate.

**Comment by folsen** [comment]
I think the story around smart contracts is a bit muddled here, I agree with some of the previous sentiment that there is a large bias towards talking and thinking about smart contracts because it is the context that people already have. A question like "How do I write smart contracts on Substrate?" is a bit confused though. The answer is you don't. You write smart contracts and deploy them to "some instance" of a Substrate-based blockchain. That might be Edgware or it might be some other smart contract platform.

In that sense, I think documentation around the contract module and ink! make the most sense in the context of some specific chain. I.E. if you want to tell the full story of writing and deploying a smart contract, it makes more sense for some concrete instance of a substrate-based chain to have that on _their_ docs site.

It is true that people will (and we want them to) re-use and extend the contracts module, but I doubt anyone will just copy-paste it as-is and use that. The contracts module is built to be a (somewhat opinionated) general smart contract platform. If one wanted to do something different, lets say a UTXO model with birth and death scripts on transaction outputs, then you can use the contract module as reference for how to do a bunch of things like sandboxing, metering etc, but it would make little sense to just use the contracts module as-is out of the box.

So, we need to have the contracts module documented well enough that people _can_ use it as reference. But I would still put an emphasis on that it makes little sense in most cases to just use the contracts module. That is, unless you want to build a generic smart contract platform.

There are two different audiences, people who want to build smart contracts, they need to find a smart contract platform to do so on. There are people who want to build a parachain, and they may want to have smart contract functionality in their chain. We need to tell a story for both groups (and there is _some_ overlap in those groups especially when it comes to experimentation and prototyping, making a dapp and then turning it into a blockchain if it makes sense etc, but this is pretty niche). I would say that we should cater more to the latter group in substrate.dev and let smart contract chains speak for themselves to the first group (but we can obviously help by giving the right pointers and setting the foundations).

> ink! being just one of the possible languages for developing against SRML Contracts means that in the long term, it may make sense to move ink! docs out of the Substrate Developer Hub.

I agree with this but also that it's probably a little early. Let's create something that can later bootstrap a site of its own. I think something we need to emphasize with ink! is the stage it's in, expectations people should have on it, the development methodology (slow-and-steady with lots of user-feedback to make sure we're building something people want) as well as vision. If someone comes in with the expectation that ink! is a ready language and they're going to use it to write smart contracts, they will be sorely disappointed. They should expect to come in and help design a good smart contract language.

I think everything under `Building/Launching Production Ready Blockchains` is sorely needed, agree with all the points there, we can probably expand more as we learn.

> Runtimes can be easily composed from existing modules
> Pluggable consensus
> Revise story around starting a new runtime

I still get a lot of questions on 1 here specifically about composability, so we can probably tell a better story here. What is the "intended use" of different models and how do they fit together?

We probably don't get as many questions on pluggable consensus as we should. The reason people should want to deal with pluggable consensus is because it is part of blockchain innovation to be able to come up with new block production mechanisms (even on Polkadot). In fact I predict that Polkadot will come up with a whole new class of block production algorithms for collators because we've now separated the security requirements for censorship resistance and finality, you get finality from Polkadot and the censorship resistance from your block production algorithm.

I think Shawns point on it being a bit early to document this really well is a good one, but we can probably document it to some degree, start getting people thinking about it and start getting them asking the right questions.

**Comment by shawntabrizi** [comment]
@folsen great to get some feedback here. I align with most of your points.

There is still lack of clarity to me on the relative priority of continuing to build ink! tutorials/docs and contract module tutorials/docs.

Especially if there is a call to action on getting users to build, experiment, and test with ink! and the contract module, we need to provide a foundation of resources for them to work with. This is why in my original vision, I had emphasized the work needed here.

**Comment by folsen** [comment]
> Especially if there is a call to action on getting users to build, experiment, and test with ink! and the contract module, we need to provide a foundation of resources for them to work with.

Completely agree, I think the difference is just how we communicate it. It is up to a specific chain to go "come here and build and deploy contracts for use" and it's up to us to go "here's how this stuff works, if you want to contribute in improving it or if you want to use any of it for your own chain".

But to that end, we still need a ton of tutorials and docs on both ink and contracts module, but IMO it should be in that context, of guiding people to helping us make it better, not as a "Here's a replacement for Solidity, use this instead".

**Comment by shawntabrizi** [comment]
@folsen Of the bullet points listed in this thread (which imply the creation or modification of some document), are there any that you don't agree with? Are there any docs not listed in this thread that you would expect to see in the near future?

I think the next logical step is to take the bullet points in this thread, and work together to stack rank them, and then allow those who want to contribute by picking from the top of the stack.

**Comment by folsen** [comment]
@shawntabrizi 

> are there any that you don't agree with?

Nope, what I'm talking about here is more things to keep in mind while writing those, and setting the tone right. Agree with the general outline and the ink! stuff looks good as a start that we'd then eventually move to a website for ink itself or something like that.

**Comment by shawntabrizi** [comment]
Closing in favor of the in progress work we are doing. Will write up a new thing
