### ISSUE TITLE
Improve Developer Hub Introduction to Substrate

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#206]
In general, the "introductory" pages for Substrate jump too deep too quickly. I want to create a set of pages on the Developer hub where you need to know nothing but the english language to be able to understand what Substrate does.

Pages could consist of something roughly like:

- [x] What is Substrate?
- [ ] Why should I care?
- [ ] What is the Substrate ecosystem?
- [ ] What is the current status of Substrate / Polkadot?
- [ ] How does Substrate compare to existing platforms?
- [ ] Next steps / Call to Action

Additionally, we should rename the content which currently resides in Substrate Fundamentals to something more.... technical sounding.

**Comment by shawntabrizi** [comment]
What is Substrate draft: https://hackmd.io/DS62xxYTTw2nnKoNXI7ZLg?view

**Comment by joepetrowski** [comment]
> Thus, Substrate’s core philosophy is to make blockchain runtime development as flexible and easy as possible.

This sentence is near the _bottom._ It should really be in the first paragraph.

# I would go at it like this:

## Intro paragraph. That sentence above should be part of it.

## What is a runtime
- This is what users care most about. We can explain the core later. 
- Here, a little context is worthwhile, like "a blockchain can be defined by its STF." 

## Stack
- Now that you've explained where the user really has the power, I'd show a simply "Core, SRML, Node" picture.
- Message: "All this stuff is what allows you to do so much awesome stuff we mentioned in the previous section!"
- SRML: I like the plug-in analogy. Mentioning how generic it is is good, but should also provide a concrete example.

## Core
- Not everyone will care about this, which is why it should come later.
- We provide all these awesome but tedious primitives like libp2p, hashing, signing, telemetry...

## Open-Source
-  This is to show that we align with the ethos of the blockchain space.

**Comment by joepetrowski** [comment]
Re: above

It's tempting to explain everything. Like how abstract/generic Substrate is, runtime upgrades, swappable consensus, offchain workers, etc. But, to me this page has two goals:

1. Make people want to dig deeper and read the other pages on dev hub and/or try a tutorial, where they will have more patience to get deep into one topic.
2. Give context to ubiquitous topics in Substrate, e.g. _what is a runtime?_

Anything that doesn't meet these should be moved to another page.

**Comment by JoshOrndorff** [comment]
This is now considered out of scope for devhub, and is the job of the comms team. This content will be part of substrate.io.

cc @thisisvilla
