### ISSUE TITLE
Organize, Refactor, and Add Runtime Recipes

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#21]
This item should be broken down into multiple new issues. 

 - [ ] Needs someone to think about whether we should have all recipes on the same page as it is now, or start to break things up and organize them

- [ ] Need to make sure that all recipes are consistent and self-sufficient to run

 - [ ] Need to think about other recipes which should be included

**Comment by shawntabrizi** [comment]
@AmarRSingh https://amarrsingh.github.io/SubstrateCookbook/main/start.html

**Comment by 4meta5** [comment]
Still a WIP in progress, but I did map what I've written thus far to the domain https://substrate.recipes/

I really think that these should be hosted separate from the Substrate Developer's Hub (and linked from there) because it contains larger code examples not dissimilar to the type of material in Cryptokitties and the TCR tutorials. Also, I've received a lot of feedback that the current formatting of recipes https://docs.substrate.dev/docs/substrate-runtime-recipes is hard to navigate and not aesthetically pleasing.

I admit that it would be nice to be able to search for recipes from the developer's hub page, but I'm curious how many people actually use this functionality and how many are pointed to the recipes. I really think we should open this up for discussion instead of limiting the conversation to me and @shawntabrizi ; I think this decision could benefit from more input.

**Comment by JoshOrndorff** [comment]
This issue is now stale. The content that was formerly at substrate.recipes is now at https://substrate.dev/recipes/

The content that was previously hosted in readme.io has been deprecated and an issue opened to restore a the missing "print a message" recipe https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/116

There is discussion about how to integrate search in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/45 and some issues we're encountering in https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/145

I'm going to close this issue. But please reopen if there is more to do. @4meta5 Are you happy with how the recipes are hosted now? If not we should reopen.
