### ISSUE TITLE
DevEx Reading Day 2019-09-13

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#241]
Please make sure to read these 5 pages from the Fuchsia documentation. It is likely we will copy these patterns nearly directly if no one calls out any issues:

* https://fuchsia.dev/fuchsia-src/best-practices/documentation_types
* https://fuchsia.dev/fuchsia-src/best-practices/documentation_standards
* https://fuchsia.dev/fuchsia-src/best-practices/documentation_comments
* https://fuchsia.dev/fuchsia-src/best-practices/documentation_style_guide
* https://fuchsia.dev/fuchsia-src/best-practices/respectful_code

---

Would be cool if people reviewed Substrate v2.0 implementation:
https://github.com/shawntabrizi/substratekitties/blob/v2.0/src/lib.rs

Would want ANY feedback or nitpick details on how this is written, as it will be the basis of our new tutorial.

---

**Comment by kaichaosun** [comment]
I was playing around with the test of coin flip game, let me know if you find something silly :)
https://github.com/kaichaosun/substrate-coin-flip/commit/5a40469e59f92c8c1c7cb4593fc2d8090465d879

**Comment by 4meta5** [comment]
Last week I added a [`treasury`](https://substrate.dev/recipes/tour/treasury.html) section to the `srml-tour` in the **recipes**. I aligned with the discussed and decided [V2 vision](https://github.com/substrate-developer-hub/recipes/issues/32) by only serving to extract patterns from this module. I think there should also be a more comprehensive walk through for the treasury as well as its runtime configuration for Polkadot -- a few people have brought this up with me in the last week, but my next priorities are sort of like:
1. add runtime configuration section to recipes
2. add `democracy` section to `srml-tour` (similar to `treasury`, extract a few simple patterns)
3. comprehensive treasury walk in context of polkadot runtime config, alongside a proposal for future governance, [wip](https://github.com/web3garden/monetary-futarchy)

One reason I am holding off on `democracy` is because the vote counting needs to use off-chain workers and I think this is already possible (*I'm looking into it now*). One useful resource for others learning about this would be [this offchain workers](https://github.com/gnunicorn/substrate-offchain-cb/blob/master/runtime/src/offchaincb.rs) tutorial by Ben, it's really simple and <200 loc so I highly recommend reading it. I think most people agree that most signal weighting and any nontrivial computation will use this API.

Outside of work, I've been getting into [lock-free algorithms](https://stjepang.github.io/2019/01/29/lock-free-rust-crossbeam-in-2019.html) recently. I think memory models like [epoch-based reclamation](https://aturon.github.io/blog/2015/08/27/epoch/#epoch-based-reclamation) will be useful when reasoning about interactions between the offchain-workers api/storage and runtime storage.

**Comment by shawntabrizi** [comment]
@JoshOrndorff Left you comments on ui template
https://github.com/substrate-developer-hub/substrate-front-end-template/issues/39

@kaichaosun left you comments on test and the ui
https://github.com/kaichaosun/substrate-coin-flip/commit/5a40469e59f92c8c1c7cb4593fc2d8090465d879
https://github.com/kaichaosun/substrate-front-end-template/pull/1

@4meta5 left you comments on the treasury pr
https://github.com/substrate-developer-hub/recipes/pull/38
