### ISSUE TITLE
substrate-front-module error

### ISSUE THREAD

**Issue by master-davidlee** [substrate-developer-hub/substrate-developer-hub.github.io#362]
hey guys  I just fellow your tutorial Creating  your first substrate chain  and when into the last chapter ,
I have already finish the .rs file  and want to copy the font-end code but it won't pass compile it says 
![Screenshot from 2019-12-10 10-05-56](https://user-images.githubusercontent.com/49427668/70488775-bb216a00-1b34-11ea-8515-fc13e1077ee9.png)

**Comment by JoshOrndorff** [comment]
You mean you've followed the tutorial all the way through this step https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/build ?

Have you re-compiled the node after adding the ProofOfExistence code to the node template? Is your code on github for me to take a look at?

**Comment by master-davidlee** [comment]
sorry bro  last two weeks i broke up .So doesn't learn at all    I will do this tutorial again to find if I was miss some steps @JoshOrndorff

**Comment by master-davidlee** [comment]
> You mean you've followed the tutorial all the way through this step https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/build ?
> 
> Have you re-compiled the node after adding the ProofOfExistence code to the node template? Is your code on github for me to take a look at?

I just do it again the same error  
![Screenshot from 2019-12-26 12-01-46](https://user-images.githubusercontent.com/49427668/71457133-828dbb80-27d7-11ea-9103-c06907e63e74.png)

**Comment by riusricardo** [comment]
@master-davidlee The issue that you have is that you're running the front-end-template using the unmodified code from the node-template. It is unable to find the storage value `proofs` because it doesn't exists in the template code. This storage value is created on the tutorial.
There are a few new changes to build the tutorial with the node-template. PR [#390 ](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/390)

**Comment by riusricardo** [comment]
Fixed. PR #390
