### ISSUE TITLE
Support tools for SRML

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#38]
In modules folder there is a `support` folder which needs documention

**Comment by AmarRSingh** [comment]
https://github.com/paritytech/substrate/issues/1981

**Comment by Kianenigma** [comment]
I can tackle this @shawntabrizi @AmarRSingh .

**Comment by shawntabrizi** [comment]
@Kianenigma please assign yourself to both issues :)

You will probably need to come up with your own template of sorts since support is quite different.

Just get the data written down, and we can iterate on format later :)

**Comment by Kianenigma** [comment]
I'll give up on this in case someone wants to take over in favor of time + it is not a priority. Some components in the support (storage, macros etc.) have already been documented as well.

**Comment by JoshOrndorff** [comment]
My understanding is that this issue is for a page on substrate.dev, _not_ reference docs. The reference docs are pretty complete already.

I'd like to get at least some common understanding of what this issue is asking for before I make a big PR. Here are some observations

Some support macro related content lives https://substrate.dev/docs/en/runtime/substrate-runtime-module-library#support-macros. Should this content be moved, or duplicated into the new page?

@shawntabrizi I believe you suggested that this page replace both of
1. https://substrate.dev/docs/en/runtime/macros/construct_runtime
2. https://substrate.dev/docs/en/runtime/macros/decl_module
That sounds like the opposite plan of what's implied by all of the `[here] (Coming Soon)` links
I prefer to leave at least the section about [when to use which runtime types](https://substrate.dev/docs/en/runtime/macros/construct_runtime#when-to-use-different-types) in tact.

**Comment by shawntabrizi** [comment]
@JoshOrndorff This is probably duplicate effort with the larger documentation of the macros and a single page talking about the macros.

Coming soon links can point directly to the reference docs where applicable.

When to use each runtime type might make the most sense in the reference docs since those types may change over time. But I defer to make that decision based on how you want to structure the final content.
