### ISSUE TITLE
Update links on https://substrate.dev/who/runtime-developer/

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#475]
See https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/474

**Comment by JoshOrndorff** [comment]
These "who" pages, like the tutorial page, are inherently troublesome because they are not versioned along with the docs that they link to. That means on each new version we will have to manually update the "who" links. Further, @thisisvilla is building an entirely new site that, as I understand, will be made public when Substrate 2.0 is launched (maybe a month from now?).

Thus, I recommend just removing the "who" pages entirely. I would be willing to do that work.

**Comment by JoshOrndorff** [comment]
Fixed in #479
