### ISSUE TITLE
why the tutorial about front-end is gone?

### ISSUE THREAD

**Issue by master-davidlee** [substrate-developer-hub/substrate-developer-hub.github.io#553]
I saw the tutorial  but it's gone  I want to know  when can I learn it again

**Comment by danforbes** [comment]
Thank you for the feedback! We will work on getting some learning materials for the front-end template up ASAP :rocket:

**Comment by master-davidlee** [comment]
Ok, Thanks! Looking forward to it

**Comment by danforbes** [comment]
I just remembered [I recently wrote some enhanced documentation for the front-end template as part of the tutorial to start your first Substrate chain](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/interact#start-the-front-end). Also, sorry for the confusion but I am closing this Issue in favor of https://github.com/substrate-developer-hub/substrate-front-end-template/issues/105 because I do not believe we will be writing a new _tutorial_ for the front-end template, but we will _definitely_ get some better documentation out there for it :rocket:
