### ISSUE TITLE
Unify links check between `yarn check-links` and in the CI Job

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#592]
`yarn check-links`:  using yarn blc
CI job: using docker image `web3f/link-checker:v1.0.1` and run `linkchecker` binary

Let's unify to use either one of them.

**Comment by jimmychu0807** [comment]
@JoshOrndorff  
How is w3f/link-checker better than `yarn blc`? Which one do you prefer?
There are some links to be excluded when checking with `yarn blc`. I am thinking if we can stick with one link-checker (or even just run `yarn check-links` in the CI) so these link-checker rules could be consistently applied.

**Comment by wheresaddie** [comment]
afaik when used in conjunction [Create Issue From File] (https://github.com/peter-evans/create-issue-from-file), issues will be created when 'linkchecker' finds issues with link-- not sure if 'yarn' implements this as well?

**Comment by danforbes** [comment]
I initially implemented link checking with `blc` and created the `yarn` task to go along with it so people could check links locally before pushing out a PR. There were some problems with `blc` (https://github.com/stevenvachon/broken-link-checker/issues/198) and so @joepetrowski and others suggested using the new approach, which is what is used in the Polkadot Wiki. I helped to implement the new approach, but neglected to remove the `yarn` task for the old approach, which I agree is not ideal. That being said, I'm not sure how to expose the new approach as some task that can be run locally so the best bet for now may just be to _remove_ the `yarn` task since there seems to be a lot of consensus around using the new approach that the Polkadot Wiki uses.

**Comment by wheresaddie** [comment]
yea-- makes sense to remove `yarn` task as we migrate to a new version then @danforbes

**Comment by jimmychu0807** [comment]
I wonder do you guys want to run `yarn check-links` and be able to run link checker? If yes, I maybe able to spend 30 mins to make `yarn check-links` to launch the docker image to run link-checker locally (given you have installed `docker`/`docker-compose`). 

If not, then I am fine to remove `yarn check-links` entirely.

**Comment by danforbes** [comment]
I think it would be worthwhile for people to be able to run the check locally :pray:
