### ISSUE TITLE
Tutorial: Minimally Viable DAO on Substrate

### ISSUE THREAD

**Issue by 4meta5** [substrate-developer-hub/substrate-developer-hub.github.io#65]
Porting MolochDAO to Substrate (in progress and will be open sourced soon!)

**Comment by JoshOrndorff** [comment]
@4meta5 I believe https://github.com/4meta5/SunshineDAO is your DAO implementation, right? Are you hoping to tutorialize it more? Is there something we should link from https://substrate.dev/en/tutorials ?

What more should we do before this issue is closed? I've assigned you, but if that is not correct, please unassign yourself.

**Comment by 4meta5** [comment]
@JoshOrndorff [SunshineDAO](https://github.com/4meta5/SunshineDAO) is the minimally viable DAO implementation, but it requires a pretty significant overhaul/rewrite and I need to add testing. For this reason, I don't want to link it from the tutorials page until this has been done because the code is buggy and disorganized right now...I also need to write more to walk through the code (like a tutorial).

I don't really have time for this at the moment (focused Beta launch todos), but will get back to it soon (by the end of this month I believe). I'll close this for now.

**Comment by 4meta5** [comment]
Actually, I'm going to take care of this ASAP. I was thinking that it is almost necessary to have a clean, up-to-date governance example for tutorial purposes. I'll focus on how I use patterns from `srml/{council, staking, democracy, balances, treasury}`.
