### ISSUE TITLE
Tutorial: Resurrect our SubstrateKitties tutorial

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#705]
Inspired by: https://vyper.fun/#/

**Comment by wheresaddie** [comment]
I think @danforbes was working on this at some point? if not, I would like to take it on if its something we see as value to the ecosystem/dev hub tutorials et all

**Comment by danforbes** [comment]
I have what I think/hope is a good start here, but I am stalled on it and could definitely use some help! https://github.com/danforbes/substratekitties

**Comment by danforbes** [comment]
@goldsteinsveta out of curiosity have you had the chance to think about this any more? Your design skillzzz would be greatly appreciated, both in terms of visual design and game/interaction design :nerd_face:

**Comment by goldsteinsveta** [comment]
yeah, I was mainly thinking how to skin the front-end template so that the **pallet** tutorial could be as interactive as possible and the result is neat and feels like a real app from 2020, without creating too much front end code. I also wanted to display some of the polkadotjs magic on the UI 🙂. Here's where I am right now:

<img width="1439" alt="Screenshot 2020-11-05 at 09 27 15" src="https://user-images.githubusercontent.com/8782596/98217404-c0588600-1f4a-11eb-98e2-06bda935393e.png">

I was not thinking about the docsify content or the character design stuff, nor about additional tutorials or overarching story behind them (ig the pokemon theme). Which are super valid aspects to think about, I guees. Let me push something to play with into dan's repo early next week? And chat about these points afterwards?

**Comment by wheresaddie** [comment]
yesssssssssssssssss love this idea @goldsteinsveta  happy to help and work with you and @danforbes to get this rolling again

**Comment by apopiak** [comment]
Happy to help out with any runtime stuff :smiley:

**Comment by wheresaddie** [comment]
@goldsteinsveta lmk when you have had a chance to push stuff or if you want to jump on a call

**Comment by NukeManDan** [comment]
@sacha-l do you have any formal work started on this?
I have a side project underway that will eventually (if you all like it) make this a cornerstone of learning substrate in a series of books. This is the rough outline: https://github.com/NukeManDan/devhub-books

Here is a community contributed FRAME V2 version to reference: https://github.com/ddimaria/substrate-collectables-workshop-template/blob/main/runtime/src/substratekitties.rs

**Comment by sacha-l** [comment]
Yes @NukeManDan ! Working on this [here](https://github.com/substrate-developer-hub/substrate-how-to-guides/tree/kitties). No particular reason for it to be in the how-to guide repo -- I'm making it a tutorial -- just want to keep things in one place =)

**Comment by NukeManDan** [comment]
https://github.com/substrate-developer-hub/substrate-docs/tree/main/v3/tutorials/11-kitties-workshop
