### ISSUE TITLE
Reference Docs Hand-off to Core Devs

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/substrate-developer-hub.github.io#77]
Ideas:

* Use CLI to make sure that docs are updated
* Add to contributor guidelines any documentation details we want to make sure makes it in
* Keep a close eye for a while
* Communicate this transition with our leadership

**Comment by JoshOrndorff** [comment]
>  Use CLI to make sure that docs are updated
I believe CI is now testing the code snippets in rust files, right?
 >   Add to contributor guidelines any documentation details we want to make sure makes it in
What's the status on this? If it isn't done, what needs to happen?
 >  Keep a close eye for a while
It's been over 3 weeks since this was opened, how are we feeling? We're supposed to be watching that any time code changes, reference docs and examples in them are updated accordingly, right? I'll start watching too.
  >  Communicate this transition with our leadership
Both Bjorn and Fred mentioned this in our 22 May all hands meeting.

**Comment by joepetrowski** [comment]
> > Use CLI to make sure that docs are updated
> 
> I believe CI is now testing the code snippets in rust files, right?

This is dependent on the example, but I believe all of our SRML docs are now tested in CI, so someone would have to explicitly change it to "ignore" or "nocompile" to make it ignore them. I hope this would get caught in review.

> > Add to contributor guidelines any documentation details we want to make sure makes it in
> 
> What's the status on this? If it isn't done, what needs to happen?

It is in @pepyakin 's guidelines that he added to the Substrate PR form. We could do a better guide on what info needs to be included.

> > Keep a close eye for a while
> 
> It's been over 3 weeks since this was opened, how are we feeling? We're supposed to be watching that any time code changes, reference docs and examples in them are updated accordingly, right? I'll start watching too.

The updates have not faced as much scrutiny as the initial pass at documentation. For example we initially decided that implementation details [like this](https://github.com/paritytech/substrate/pull/2694#discussion_r288527917) wouldn't go into the docs because it's way too difficult to maintain.
