### ISSUE TITLE
Node template code walk through

### ISSUE THREAD

**Issue by kaichaosun** [substrate-developer-hub/substrate-developer-hub.github.io#777]
Substrate based developers usually starts with node template.
It's not easy to understand the whole part of node template.
If we have a page to detail every part of node template, it should help a lot of people and make them more confident in their early journey.

**Comment by wheresaddie** [comment]
this is a great point @kaichaosun , @danforbes has been the one wanting to admin the tutorials so I will default to him to respond.

**Comment by danforbes** [comment]
Have you seen the documentation that was added to the README of the Node Template? https://github.com/substrate-developer-hub/substrate-node-template#template-structure

**Comment by kaichaosun** [comment]
Yeah, I'm aware of it, the content in README looks great.
Will it be better to enrich it if needed and make it live in dev hub docs?
Also add line by line comments in node template just like the template pallet seems helpful to devs.

**Comment by danforbes** [comment]
In which section of the Dev Hub would you see this documentation living? As you said in your initial comment, Substrate developers usually start from the Node Template so to me it makes sense to include this documentation with the Node Template, especially since the information we are documenting is directly related to the Node Template itself.

With respect to more line-by-line comments in the Node Template this is definitely the sort of thing I'd love to see. Anywhere in particular you think we should start?

**Comment by kaichaosun** [comment]
I would imagine there is a page in devhub to teach the user how to assemble a working node (in our case it's node template). I believe the content in README should be good at first.
For the comments in node-template, I guess we need to start in the substrate repo, then sync to node-template, but I'm not sure about the relationship between substrate/node-template and devhub/node-template.

**Comment by NukeManDan** [comment]
For the curious, this is how the substrate template is produced (on a rolling release basis, presently monthly)
https://github.com/paritytech/substrate/blob/master/docs/node-template-release.md
