### ISSUE TITLE
Review & update Tutorial: ink! Smart Contracts Tutorial to v3 compatible

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-developer-hub.github.io#889]
https://substrate.dev/tutorials/ink-smart-contracts-tutorial/

There may be a lot of rewrite, since pallet-contracts has been updated to v3.0.0 and probably lots of breaking API changes.

**Comment by riusricardo** [comment]
This one is compatible with v3.0 it just need updates on the screenshots because Canvas UI isn't working as expected. It should be changed to polkadot js apps

**Comment by jimmychu0807** [comment]
thanks @riusricardo

**Comment by jimmychu0807** [comment]
self-note: test run the tutorial with v3.0 smart contract.

**Comment by riusricardo** [comment]
There's another change that will impact this tutorial. I want to see how to mitigate it. The main Canvas node is gonna become a parachain and it will complicate a few things.
We could change and point to the testnet instead of running it locally, but I just need a little bit more time to analyze this. I want to keep it without introducing parachains for now.

**Comment by NukeManDan** [comment]
There was an [announcement](https://matrix.to/#/!OEoEzWHbyVSzzkIWQw:matrix.parity.io/$gcDY-7lDQaEjsG_HaxzSaEyGG4DRUkUCNPLLV1Sbv2k?via=matrix.parity.io&via=matrix.org&via=web3.foundation) and release of canvas, might be worth updating to use this? 

https://github.com/paritytech/cargo-contract/releases/tag/v0.11.0
